### ISSUE TITLE
IllegalStateException: startRecording() called on an uninitialized AudioRecord

### ISSUE THREAD

**Issue by jpage4500** [pedroSG94/AndroidReStreamer#5]
Hi, I'm looking at this project to see the RTMP library in action.. I noticed it's using an older version of the library but when running I get the following Exception:

I tried updating the library to the latest but it requires code changes so I figured I'd post here first before trying that

```
10-25 15:03:51.702	com.streye.androidrestreamer	31819	-	E	SurfaceView	 Exception configuring surface
10-25 15:03:51.702	com.streye.androidrestreamer	31819	-	E	SurfaceView	 java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord.
10-25 15:03:51.702	com.streye.androidrestreamer	31819	-	E	SurfaceView	 	at android.media.AudioRecord.startRecording(AudioRecord.java:1142)
10-25 15:03:51.702	com.streye.androidrestreamer	31819	-	E	SurfaceView	 	at com.pedro.encoder.input.audio.MicrophoneManager.init(MicrophoneManager.java:85)
10-25 15:03:51.702	com.streye.androidrestreamer	31819	-	E	SurfaceView	 	at com.pedro.encoder.input.audio.MicrophoneManager.start(MicrophoneManager.java:66)
10-25 15:03:51.702	com.streye.androidrestreamer	31819	-	E	SurfaceView	 	at com.streye.androidrestreamer.plugin.VLCReStreamerBase.startEncoders(VLCReStreamerBase.kt:254)
10-25 15:03:51.702	com.streye.androidrestreamer	31819	-	E	SurfaceView	 	at com.streye.androidrestreamer.plugin.VLCReStreamerBase.startStream(VLCReStreamerBase.kt:241)
10-25 15:03:51.702	com.streye.androidrestreamer	31819	-	E	SurfaceView	 	at com.streye.androidrestreamer.MainActivity.surfaceChanged(MainActivity.kt:53)
10-25 15:03:51.702	com.streye.androidrestreamer	31819	-	E	SurfaceView	 	at android.view.SurfaceView.updateSurface(SurfaceView.java:1165)
10-25 15:03:51.702	com.streye.androidrestreamer	31819	-	E	SurfaceView	 	at android.view.SurfaceView.lambda$new$0$SurfaceView(SurfaceView.java:173)
10-25 15:03:51.702	com.streye.androidrestreamer	31819	-	E	SurfaceView	 	at android.view.-$$Lambda$SurfaceView$w68OV7dB_zKVNsA-r0IrAUtyWas.onPreDraw(Unknown Source:2)
10-25 15:03:51.702	com.streye.androidrestreamer	31819	-	E	SurfaceView	 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)
10-25 15:03:51.702	com.streye.androidrestreamer	31819	-	E	SurfaceView	 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3094)
10-25 15:03:51.702	com.streye.androidrestreamer	31819	-	E	SurfaceView	 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
10-25 15:03:51.702	com.streye.androidrestreamer	31819	-	E	SurfaceView	 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8177)
10-25 15:03:51.702	com.streye.androidrestreamer	31819	-	E	SurfaceView	 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
10-25 15:03:51.702	com.streye.androidrestreamer	31819	-	E	SurfaceView	 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
10-25 15:03:51.702	com.streye.androidrestreamer	31819	-	E	SurfaceView	 	at android.view.Choreographer.doFrame(Choreographer.java:731)
10-25 15:03:51.702	com.streye.androidrestreamer	31819	-	E	SurfaceView	 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
10-25 15:03:51.702	com.streye.androidrestreamer	31819	-	E	SurfaceView	 	at android.os.Handler.handleCallback(Handler.java:938)
10-25 15:03:51.702	com.streye.androidrestreamer	31819	-	E	SurfaceView	 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-25 15:03:51.702	com.streye.androidrestreamer	31819	-	E	SurfaceView	 	at android.os.Looper.loop(Looper.java:223)
10-25 15:03:51.702	com.streye.androidrestreamer	31819	-	E	SurfaceView	 	at android.app.ActivityThread.main(ActivityThread.java:7660)
10-25 15:03:51.702	com.streye.androidrestreamer	31819	-	E	SurfaceView	 	at java.lang.reflect.Method.invoke(Native Method)
10-25 15:03:51.702	com.streye.androidrestreamer	31819	-	E	SurfaceView	 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-25 15:03:51.702	com.streye.androidrestreamer	31819	-	E	SurfaceView	 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

**Comment by jpage4500** [comment]
answering my own question.. I just needed to give all permissions to the app (it doesn't prompt for them so i had to use app info screen).. in case anyone else has the same problem!
